# Site settings
# baseurl: http://alecive.github.io/lista-bimbo-roncioppi
title: Lista bimbo
email: alecive87@gmail.com
url: https://alecive.github.io/lista-bimbo-roncioppi
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Per il figlio dei Roncioppiiii"
meta_author: Alessandro Roncone

# Google webmaster tools
google_verify: 1fM5KCFImdJuWeo8L_Qo7_-tuItbZ5hoIlGg8g14WkY

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: acd1e9 #80B3FF
  primary-rgb: "172,209,233" #"128,179,255"
  secondary: 6d929b #FD6E8A
  secondary-dark: 6d929b #A2122F


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/alecive

# Build settings
markdown: kramdown
permalink: pretty
